# ------------------------
# Stage 1: Build & Test
# ------------------------
FROM FROM node:18-alpine AS builder

# Set working directory
WORKDIR /node

# Copy package files first for caching
COPY package*.json ./

# Install ALL dependencies (including devDependencies)
RUN npm install 
# Copy application source
COPY . .




# ------------------------
# Stage 2: Production
# ------------------------
FROM gcr.io/distroless/nodejs18

WORKDIR /node

# Copy only package files
COPY --from=builder /node/package*.json ./
COPY --from=builder /node/node_modules ./node_modules

# Copy application source
COPY --from=builder /node .

EXPOSE 8000

CMD ["app.js"]


